function axonDelays =...
  calculateAxonDelaysDV(DVMP, chosenTargets, distancesSquared)



  conductionSpeed = DVMP.FATS*1000;
  axonDelays = (sqrt(distancesSquared(chosenTargets, 1) + ...
                    distancesSquared(chosenTargets, 2) + ...
                    distancesSquared(chosenTargets, 3)) ./ ...
                    conductionSpeed);

end