% This script will reproduce the results figures in the VERTEX 2.0 paper. 

%% Data file locations
F1000_data_dir = '/media/b3046588/Elements/F1000_Data/';
%% Uncomment this if you are analysing the data provided 
singlePulseDir = [F1000_data_dir filesep 'singlepulse' filesep 'singlepulse_1001'];
multipleRunsDir = [F1000_data_dir filesep 'singlepulse' filesep 'multipleRuns' filesep];
nosynapseDir = [F1000_data_dir filesep 'singlepulse' filesep 'no_synapses' filesep  'singlepulse_1001'];
synapticcurrentsDir = [F1000_data_dir filesep 'singlepulse' filesep 'singlepulse_1001_I_synComp'];
membranecurrentsDir = [F1000_data_dir filesep 'singlepulse' filesep 'singlepulse_1001_I_syn_csd'];

pairedPulseDir = [F1000_data_dir filesep 'pairedpulse' filesep ];
pairedPulseDetailed = [F1000_data_dir filesep 'pairedpulse' filesep 'pairedpulse1001_detailed' ];
pairedPulseI_synComp = [F1000_data_dir filesep 'pairedpulse' filesep 'pairedpulse1001_I_synComp' ];

tbsDir = [F1000_data_dir filesep 'tbs' filesep];
tbs1001Dir = [tbsDir filesep 'tbs_1001'];
tbsWithWeights = [tbsDir filesep 'tbs_1001_weights' filesep];

%% Uncomment this if you are analysing data generated by the singlepulse, nosynapse, pairedPulse, and thetaburststimulation scripts.
% singlePulseDir = [F1000_data_dir filesep 'singlepulse_1001'];
% nosynapseDir = [F1000_data_dir filesep  'nosynapse_1001'];
% synapticcurrentsDir = singlePulseDir;
% membranecurrentsDir = singlePulseDir;
% 
% pairedPulseDir = [F1000_data_dir filesep 'pairedpulse_1001'];
% pairedPulseDetailed = pairedPulseDir;
% pairedPulseI_synComp = pairedPulseDir;
% 
% tbsDir = [F1000_data_dir];
% tbs1001Dir = [tbsDir filesep 'tbs_1001'];
% tbsWithWeights = tbs1001Dir;



%% Figure 10 A and C
RecordingSettings.saveDir = singlePulseDir;
Results = loadResults(RecordingSettings.saveDir,1);
spikeIDs =  Results.spikes(Results.spikes(:,2)>Results.params.TissueParams.StimulationOn & ...
    Results.spikes(:,2)<Results.params.TissueParams.StimulationOff,1);
%Figure 10(A) Neurons recruited directly by stimulation plotted spatially.
plotsomapositions(Results, spikeIDs);

%Figure 10(C) Spike raster of the entire slice during stimulation and
%after.
rasterParams.colors = {'k','m','m','m','m','k','k','k','m','m','m','m','k','k','k','k','m','m','m','m','k','k','k','k','k','m','m','m','m'};
%plot the slice simulation spike raster, each dot represents the time(on the x axis) at
%which the neuron of a particular id (on the y axis) fired. 
rasterParams.groupBoundaryLines = 'c';
rasterParams.title = 'Spike Raster';
rasterParams.xlabel = 'Time (ms)';
rasterParams.ylabel = 'Neuron ID';
rasterParams.figureID = 2;
N = Results.params.TissueParams.N;
rasterParams.neuronsToPlot = 1:N;
rasterFigureImproved = plotSpikeRaster(Results, rasterParams);

%% Figure 10 B and D
% Figure 10(B) Mean and STD of proportion of each cell type recruited
% directly by stimulation.
path = [multipleRunsDir 'singlepulse_100'];
figure;
plotMeanRecruitment; 
%
%Figure 10(D) Breakdown of the LFP produced by the response to stimulus.
% Showing the contribution of each neuron type.
RecordingSettings.saveDir = singlePulseDir;
Results = loadResults(RecordingSettings.saveDir,0);
RecordingSettings.saveDir = nosynapseDir;
ResultsNoSyn = loadResults(RecordingSettings.saveDir,0);
getContributions(Results.LFP, 2, [7500 9800], ResultsNoSyn.LFP, getTimeVector(Results,'ms'));

%% Figure 11
% (A) LFP without stimulus artifact
figure;
t = getTimeVector(Results,'ms');
plot(t(7500:9800), Results.LFP{13}(2,7500:9800)-ResultsNoSyn.LFP{13}(2,7500:9800));
%%
% (C) Synaptic current arriving at each compartment of the cell
RecordingSettings.saveDir = synapticcurrentsDir;
Results = loadResults(RecordingSettings.saveDir,0);
NP = Results.params.NeuronParams(14);
NP.labelnames = {'somaID','basalID','obliqueID','apicalID','trunkID','tuftID'};
times = [7000 10000];
figure;
plotCSDSingleNeuron(Results, Results.I_synComp{1},times,NP);
%%
% (B) Synaptic current grouped by presynaptic neuron group
RecordingSettings.saveDir = membranecurrentsDir;
Results = loadResults(RecordingSettings.saveDir,0);
plotCellCurrents(Results,1:50,1,[7500 9800]);
%
% (D) Transmembrane current at each compartment and 
% (E) LFP generated by
% each compartment.

plotLFPbycompartment;

%% Figure 12

path = [pairedPulseDir filesep 'multipleRuns' filesep 'pairedpulse_'];
% (C) Mean recruitment of TTPC cells during stimulation
figure;
plotMeanRecruitmentPP;
% (D) Mean levels of residual inhibitory current received by the population
% of TTPC cells recruited directly by the first stimulus.
figure;
plotMeanResidualInhibitionPP;
figure;
% (B) Mean amplitude difference between first and second pulse for two
% components of the response.

plotPPresponseamps;

%% Figure 13 
RecordingSettings.saveDir = pairedPulseDetailed;
Results = loadResults(RecordingSettings.saveDir,1);
figure;
% Top pane
plotPPsynapticresources;
%Bottom pane
plotLFPbycompartment;
%% 
RecordingSettings.saveDir = pairedPulseI_synComp;
Results = loadResults(RecordingSettings.saveDir,1);
%%
NP = Results.params.NeuronParams(14);
NP.labelnames = {'somaID','basalID','obliqueID','apicalID','trunkID','tuftID'};
times = [1500 6000];
figure;
%Middle pane
plotCSDSingleNeuron(Results, Results.I_synComp{1},times);

%%


%% Figure 14
RecordingSettings.saveDir = tbs1001Dir;
Results = loadResults(RecordingSettings.saveDir,1);
figure;
t = getTimeVector(Results, 's');
plot(t(2000:18000),Results.LFP(2,2000:18000));
%%
rasterParams.colors = {'k','m','m','m','m','k','k','k','m','m','m','m','k','k','k','k','m','m','m','m','k','k','k','k','k','m','m','m','m'};

%plot the slice simulation spike raster, each dot represents the time(on the x axis) at
%which the neuron of a particular id (on the y axis) fired. 
rasterParams.groupBoundaryLines = 'c';
rasterParams.title = 'Spike Raster';


rasterParams.xlabel = 'Time (ms)';
rasterParams.ylabel = 'Neuron ID';
N = Results.params.TissueParams.N;
rasterParams.figureID = 17;

rasterParams.neuronsToPlot = 1:N;
rasterFigureImproved = plotSpikeRaster(Results, rasterParams);
%% Figure 15 B, C, D
RecordingSettings.saveDir = tbsWithWeights;
Results = loadResults(RecordingSettings.saveDir,1);

% (B) 
figure;
plotstdpchangesandspikes(50000,100000, Results);
% (C) 
figure;
plotweightchangespatial;
figure;
plotweightchangesbygroup;

%% Figure 15 A
path = [tbsDir filesep 'multipleRuns' filesep 'tbs_'];
figure;
plotLTPLFP;

